run_tag: '2048_tiny'
env_config: {
  env_type: '2048',
}
model_config: { # overwritten if loading a checkpoint
  res_channels: 16,
  res_blocks: 6,
  kernel_size: 3,
  value_fc_size: 32,
  value_output_activation: ""
}
train_mode_config: {
  algo_config: {
    name: "alphazero",
    temperature: 0.0,
    num_iters: 400,
    max_nodes: 400,
    puct_coeff: 1.0,
    dirichlet_alpha: 0.1,
    dirichlet_epsilon: 0.0,
  },
  learning_rate: 0.1,
  momentum: 0.8,
  c_reg: 0.0001,
  lr_decay_gamma: 0.9,
  replay_memory_sample_games: True,
  replay_memory_max_size: 20000,
  replay_memory_min_size: 20000,
  parallel_envs: 8192,
  policy_factor: 1.0,
  minibatch_size: 4096,
  episodes_per_epoch: 20000,
  episodes_per_minibatch: 1,
  test_config: {
    algo_config: {
      name: "lazyzero",
      temperature: 0.0,
      num_policy_rollouts: 100,
      rollout_depth: 2,
      puct_coeff: 1.0,
    },
    episodes_per_epoch: 0
  }
}
