run_tag: 'asmr_mini'
env_config: {
  env_type: 'ASMR',
  matrix_dim: 1,
  min_initial_set_size: 1,
  max_initial_set_size: 1,
  normal_std_dev: 1.0,
  max_num_turns: 2,
  discount_factor: 0.01,
}
model_config: { # overwritten if loading a checkpoint
  feature_maps: 128,
  layers: 40,
}
train_mode_config: {
  algo_config: {
    name: "alphazero",
    temperature: 1.0,
    num_iters: 100,
    max_nodes: 40,
    puct_coeff: 1.0,
    dirichlet_alpha: 0.45,
    dirichlet_epsilon: 0.25
  },
  learning_rate: 0.1,
  lr_decay_gamma: 0.8,
  momentum: 0.9,
  c_reg: 0.0001,
  replay_memory_max_size: 20000,
  replay_memory_min_size: 4,
  parallel_envs: 4,
  policy_factor: 1.0,
  minibatch_size: 4,
  episodes_per_epoch: 4,
  episodes_per_minibatch: 4,
  test_config: {
    algo_config: {
      name: "alphazero",
      temperature: 0.0,
      num_iters: 1000,
      max_nodes: 400,
      puct_coeff: 1.0,
      dirichlet_alpha: 0.1,
      dirichlet_epsilon: 0.0
    },
    episodes_per_epoch: 256,
  }
}
